In [1]:
import pandas as pd
from sqlalchemy import create_engine
#from secret import connection_string

In [2]:
csv_file = "../Run Data/world-marathon-majors/Female_Elite_Boston.csv"
female_runner_data = pd.read_csv(csv_file,low_memory= True, encoding ='iso8859_15')
female_runner_data.head(20)

,Year,Athlete,Country,Time,Notes,State
0,1966,Bobbi Gibb,United States,3:21:40,(unsanctioned)[4],MA
1,1967,Bobbi Gibb,United States,3:27:17,(unsanctioned) 2nd victory[4],CA
2,1968,Bobbi Gibb,United States,3:30:00,(unsanctioned) 3rd victory[4],CA
3,1969,Mae Berman,United States,3:22:46,(unsanctioned)[4],MA
4,1970,Mae Berman,United States,3:05:07,(unsanctioned) 2nd victory[4],MA
5,1971,Mae Berman,United States,3:08:30,(unsanctioned) 3rd victory[4],MA
6,1972,Nina Kuscsik,United States,3:10:26,first year that women were officially sanctioned,NY
7,1973,Jacqueline Hansen,United States,3:05:59,NaN,CA
8,1974,Miki Gorman,United States,2:47:11,NaN,CA
9,1975,Liane Winter,Germany West,2:42:24,NaN,NaN
10,1976,Kim Merritt,United States,2:47:10,NaN,WI
11,1977,Miki Gorman,United States,2:48:33,2nd victory,CA
12,1978,Gayle Barron,United States,2:44:52,NaN,GA
13,1979,Joan Benoit,United States,2:35:15,NaN,ME
14,1980,Jacqueline Gareau,Canada,2:34:28,NaN,NaN
15,1981,Allison Roe,Zealand New,2:26:46,NaN,NaN
16,1982,Charlotte Teske,Germany West,2:29:33,NaN,NaN
17,1983,Joan Benoit,United States,2:22:43,2nd victory,ME
18,1984,Lorraine Moller,Zealand New,2:29:28,NaN,NaN
19,1985,Larsen Weidenbach,United States,2:34:06,NaN,MI

In [3]:
female_runner_data = female_runner_data.dropna(axis = 1 , how = 'any')
clean_female_runner_data = female_runner_data[['Year','Athlete', 'Country','Time']].copy()

In [4]:
clean_female_runner_data.set_index("Year",inplace = True)

In [5]:
clean_female_runner_data.head(50)

                 Athlete        Country     Time
Year
1966          Bobbi Gibb  United States  3:21:40
1967          Bobbi Gibb  United States  3:27:17
1968          Bobbi Gibb  United States  3:30:00
1969          Mae Berman  United States  3:22:46
1970          Mae Berman  United States  3:05:07
1971          Mae Berman  United States  3:08:30
1972        Nina Kuscsik  United States  3:10:26
1973   Jacqueline Hansen  United States  3:05:59
1974         Miki Gorman  United States  2:47:11
1975        Liane Winter   Germany West  2:42:24
1976         Kim Merritt  United States  2:47:10
1977         Miki Gorman  United States  2:48:33
1978        Gayle Barron  United States  2:44:52
1979         Joan Benoit  United States  2:35:15
1980   Jacqueline Gareau         Canada  2:34:28
1981         Allison Roe    Zealand New  2:26:46
1982     Charlotte Teske   Germany West  2:29:33
1983         Joan Benoit  United States  2:22:43
1984     Lorraine Moller    Zealand New  2:29:28
1985   Larsen Weidenbach  United States  2:34:06
1986  Ingrid Kristiansen         Norway  2:24:55
1987           Rosa Mota       Portugal  2:25:21
1988           Rosa Mota       Portugal  2:24:30
1989  Ingrid Kristiansen         Norway  2:24:33
1990           Rosa Mota       Portugal  2:25:24
1991        Wanda Panfil         Poland  2:24:18
1992        Olga Markova         Russia  2:23:43
1993        Olga Markova         Russia  2:25:27
1994          Uta Pippig        Germany  2:21:45
1995          Uta Pippig        Germany  2:25:11
1996          Uta Pippig        Germany  2:27:12
1997         Fatuma Roba       Ethiopia  2:26:23
1998         Fatuma Roba       Ethiopia  2:23:21
1999         Fatuma Roba       Ethiopia  2:23:25
2000   Catherine Ndereba          Kenya  2:26:11
2001   Catherine Ndereba          Kenya  2:23:53
2002      Margaret Okayo          Kenya  2:20:43
2003  Svetlana Zakharova         Russia  2:25:19
2004   Catherine Ndereba          Kenya  2:24:27
2005   Catherine Ndereba          Kenya  2:25:12
2006         Rita Jeptoo          Kenya  2:23:38
2007   Lidiya Grigoryeva         Russia  2:29:18
2008           Dire Tune       Ethiopia  2:25:25
2009       Salina Kosgei          Kenya  2:32:16
2010       Teyba Erkesso       Ethiopia  2:26:11
2011      Caroline Kilel          Kenya  2:22:36
2012       Sharon Cherop          Kenya  2:31:50
2013         Rita Jeptoo          Kenya  2:26:25
2014         Rita Jeptoo          Kenya  2:18:57
2014       Buzunesh Deba       Ethiopia  2:19:59

In [6]:
csv_file = "../Run Data/world-marathon-majors/Male_Elite_Boston.csv"

male_runner_data = pd.read_csv(csv_file,low_memory= True, encoding ='iso8859_15')
male_runner_data.head(20)

    Year             Athlete        Country     Time        Notes State
0   1897      John McDermott  United States  2:55:10          NaN    NY
1   1898    Ronald MacDonald         Canada  2:42:00          NaN    NS
2   1899  Lawrence Brignolia  United States  2:54:38          NaN    MA
3   1900        Jack Caffery         Canada  2:39:44          NaN    ON
4   1901        Jack Caffery         Canada  2:29:23  2nd victory    ON
5   1902        Sammy Mellor  United States  2:43:12          NaN    NY
6   1903         John Lorden  United States  2:41:29          NaN    MA
7   1904      Michael Spring  United States  2:38:04          NaN    NY
8   1905      Frederick Lorz  United States  2:38:25          NaN    NY
9   1906            Tim Ford  United States  2:45:45          NaN    MA
10  1907     Thomas Longboat         Canada  2:24:24          NaN    ON
11  1908    Thomas Morrissey  United States  2:25:43          NaN    NY
12  1909        Henri Renaud  United States  2:53:36          NaN    NH
13  1910        Fred Cameron         Canada  2:28:52          NaN    NS
14  1911      Clarence DeMar  United States  2:21:39          NaN    MA
15  1912        Michael Ryan  United States  2:21:18          NaN    NY
16  1913       Fritz Carlson  United States  2:25:14          NaN    MN
17  1914         James Duffy         Canada  2:25:14          NaN    ON
18  1915         Fabre Fabre         Canada  2:31:41          NaN    PQ
19  1916         Arthur Roth  United States  2:27:16          NaN    MA

In [7]:
clean_male_runner_data = male_runner_data[['Year','Athlete','Country','Time']].copy()

In [8]:
clean_male_runner_data.set_index("Year",inplace = True)

In [9]:
clean_male_runner_data

                 Athlete        Country     Time
Year
1897      John McDermott  United States  2:55:10
1898    Ronald MacDonald         Canada  2:42:00
1899  Lawrence Brignolia  United States  2:54:38
1900        Jack Caffery         Canada  2:39:44
1901        Jack Caffery         Canada  2:29:23
1902        Sammy Mellor  United States  2:43:12
1903         John Lorden  United States  2:41:29
1904      Michael Spring  United States  2:38:04
1905      Frederick Lorz  United States  2:38:25
1906            Tim Ford  United States  2:45:45
1907     Thomas Longboat         Canada  2:24:24
1908    Thomas Morrissey  United States  2:25:43
1909        Henri Renaud  United States  2:53:36
1910        Fred Cameron         Canada  2:28:52
1911      Clarence DeMar  United States  2:21:39
1912        Michael Ryan  United States  2:21:18
1913       Fritz Carlson  United States  2:25:14
1914         James Duffy         Canada  2:25:14
1915         Fabre Fabre         Canada  2:31:41
1916         Arthur Roth  United States  2:27:16
1917        Bill Kennedy  United States  2:28:37
1918         Camp Devens  United States  2:29:53
1919         Carl Linder  United States  2:29:13
1920   Peter Trivoulides         Greece  2:29:31
1921          Frank Zuna  United States  2:18:57
1922      Clarence DeMar  United States  2:18:10
1923      Clarence DeMar  United States  2:23:47
1924      Clarence DeMar  United States  2:29:40
1925      Charles Mellor  United States  2:33:00
1926        Johnny Miles         Canada  2:25:40
...                  ...            ...      ...
1989      Abebe Mekonnen       Ethiopia  2:09:06
1990      Gelindo Bordin          Italy  2:08:19
1991     Ibrahim Hussein          Kenya  2:11:06
1992     Ibrahim Hussein          Kenya  2:08:14
1993        Cosmas Ndeti          Kenya  2:09:33
1994        Cosmas Ndeti          Kenya  2:07:15
1995        Cosmas Ndeti          Kenya  2:09:22
1996         Moses Tanui          Kenya  2:09:15
1997        Lameck Aguta          Kenya  2:10:34
1998         Moses Tanui          Kenya  2:07:34
1999       Joseph Chebet          Kenya  2:09:52
2000        Elijah Lagat          Kenya  2:09:47
2001             Bong Ju    South Korea  2:09:43
2002         Rodgers Rop          Kenya  2:09:02
2003  Kipkoech Cheruiyot          Kenya  2:10:11
2004    Timothy Cherigat          Kenya  2:10:37
2005      Hailu Negussie       Ethiopia  2:11:44
2006  Kipkoech Cheruiyot          Kenya  2:07:14
2007  Kipkoech Cheruiyot          Kenya  2:14:13
2008  Kipkoech Cheruiyot          Kenya  2:07:45
2009        Deriba Merga       Ethiopia  2:08:42
2010   Kiprono Cheruiyot          Kenya  2:05:52
2011      Geoffrey Mutai          Kenya  2:03:02
2012        Wesley Korir          Kenya  2:12:40
2013        Desisa Benti       Ethiopia  2:10:22
2014      Meb Keflezighi  United States  2:08:37
2015        Desisa Benti       Ethiopia  2:09:17
2016       Berhanu Hayle       Ethiopia  2:12:45
2017      Geoffrey Kirui          Kenya  2:09:37
2018       Yuki Kawauchi          Japan  2:15:58

[122 rows x 3 columns]

In [10]:
rds_connection_string = "postgres:Juju03Rio!@localhost/runner_data"
engine = create_engine(f'postgres://{rds_connection_string}')

In [11]:
engine.table_names()

['female_boston', 'male_boston']

In [12]:
clean_female_runner_data.to_sql(name ='female_boston', con = engine, if_exists = 'replace')

In [13]:
clean_male_runner_data.to_sql(name='male_boston', con=engine, if_exists = 'replace')

In [14]:
pd.read_sql_query('select * from female_boston',con= engine ).head(20)

    Year            Athlete        Country     Time
0   1966         Bobbi Gibb  United States  3:21:40
1   1967         Bobbi Gibb  United States  3:27:17
2   1968         Bobbi Gibb  United States  3:30:00
3   1969         Mae Berman  United States  3:22:46
4   1970         Mae Berman  United States  3:05:07
5   1971         Mae Berman  United States  3:08:30
6   1972       Nina Kuscsik  United States  3:10:26
7   1973  Jacqueline Hansen  United States  3:05:59
8   1974        Miki Gorman  United States  2:47:11
9   1975       Liane Winter   Germany West  2:42:24
10  1976        Kim Merritt  United States  2:47:10
11  1977        Miki Gorman  United States  2:48:33
12  1978       Gayle Barron  United States  2:44:52
13  1979        Joan Benoit  United States  2:35:15
14  1980  Jacqueline Gareau         Canada  2:34:28
15  1981        Allison Roe    Zealand New  2:26:46
16  1982    Charlotte Teske   Germany West  2:29:33
17  1983        Joan Benoit  United States  2:22:43
18  1984    Lorraine Moller    Zealand New  2:29:28
19  1985  Larsen Weidenbach  United States  2:34:06

In [15]:
pd.read_sql_query('select * from male_boston',con= engine ).head(20)

    Year             Athlete        Country     Time
0   1897      John McDermott  United States  2:55:10
1   1898    Ronald MacDonald         Canada  2:42:00
2   1899  Lawrence Brignolia  United States  2:54:38
3   1900        Jack Caffery         Canada  2:39:44
4   1901        Jack Caffery         Canada  2:29:23
5   1902        Sammy Mellor  United States  2:43:12
6   1903         John Lorden  United States  2:41:29
7   1904      Michael Spring  United States  2:38:04
8   1905      Frederick Lorz  United States  2:38:25
9   1906            Tim Ford  United States  2:45:45
10  1907     Thomas Longboat         Canada  2:24:24
11  1908    Thomas Morrissey  United States  2:25:43
12  1909        Henri Renaud  United States  2:53:36
13  1910        Fred Cameron         Canada  2:28:52
14  1911      Clarence DeMar  United States  2:21:39
15  1912        Michael Ryan  United States  2:21:18
16  1913       Fritz Carlson  United States  2:25:14
17  1914         James Duffy         Canada  2:25:14
18  1915         Fabre Fabre         Canada  2:31:41
19  1916         Arthur Roth  United States  2:27:16